### ISSUE TITLE
感谢分享，要是能够有属性内容就好了

### ISSUE THREAD

**Issue by zjumelody** [Majjcom/ncmDumper#1]
客户端好像是通过音频文件的属性内容来定位判断这是哪首歌，所以如果能够在转换格式的时候原样保留文件属性内容就好了，这样转换后的文件可以直接被客户端识别，可以实现不，还是说这个属性内容ncm格式里就没有而是客户端通过其他方式定位的呢

**Comment by Majjcom** [comment]
那些数据主要储存在文件的`mata data`里面，以后有空研究一下

**Comment by Majjcom** [comment]
我这边是把除封面以外的其他`mataData`都原封不动地导出
无法识别大概率是客户端对有版权保护的音频只认`ncm`文件，其他概不识别
